name: Nick Brooks
repository: nickbrooks/nickbrooks.github.io.
markdown: kramdown
permalink: /blog/:title
gems:
  - jekyll-sitemap
exclude:
  - package.json
  - _dev
  - node_modules
  - gulpfile.js
  - readme.md